---
fixtures:
  forge_modules:
    service: "puppetlabs/service"
    package: "puppetlabs/package"
    reboot: "puppetlabs/reboot"
  repositories:
    cron_core: "https://github.com/puppetlabs/puppetlabs-cron_core"
    facts: 'https://github.com/puppetlabs/puppetlabs-facts'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent'
    provision: 'https://github.com/puppetlabs/provision'
    bootstrap: 'https://github.com/puppetlabs/puppetlabs-bootstrap'
    puppet_conf: 'https://github.com/puppetlabs/puppetlabs-puppet_conf'
    deploy_pe: 'https://github.com/jarretlavallee/puppet-deploy_pe'
    ruby_task_helper: 'https://git@github.com/puppetlabs/puppetlabs-ruby_task_helper'
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib'
    bash_task_helper: 'https://github.com/puppetlabs/puppetlabs-bash_task_helper'
    node_manager: 'https://github.com/MartyEwings/puppet-node_manager.git'
    apply_helpers: 'https://github.com/puppetlabs/puppetlabs-apply_helpers'
    debug: 'https://github.com/nwops/puppet-debug'
    format: 'https://github.com/voxpupuli/puppet-format'
    container_inventory: 'https://gitlab.com/nwops/bolt-container_inventory'
    peadm: 'https://github.com/puppetlabs/puppetlabs-peadm.git'
  symlinks:
    peadm_spec: "#{source_dir}/spec/fixtures/modules/peadm/spec/acceptance/peadm_spec/"
    puppetlabs-puppet_metrics_collector: "#{source_dir}"
